name: Create Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential librust-atk-sys-dev libgtk-3-dev gcc-multilib libpq-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run tests
      run: cargo test --verbose
          
  build_release:
    name: Build Release
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: macos-latest
            release_suffix: mac
          - os: windows-latest
            release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get update
          sudo apt-get install build-essential librust-atk-sys-dev libgtk-3-dev gcc-multilib libpq-dev libxcb-shape0-dev libxcb-xfixes0-dev
          
      - name: Optimized build
        run: cargo build --release

      - name: Deploy Release Mac & Linux
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/gamercade-io/gamercade_console/releases/73475292/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          release_id: 73475292 # same as above (id can just be taken out the upload_url, it's used to find old releases)
          asset_path: ./target/release/gamercade_console
          asset_name: gamercade_console-${{ matrix.release_suffix }}
          asset_content_type: application/zip # required by GitHub API
          
      - name: Deploy Release Windows   
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/gamercade-io/gamercade_console/releases/73475292/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          release_id: 73475292 # same as above (id can just be taken out the upload_url, it's used to find old releases)
          asset_path: ./target/release/gamercade_console.exe
          asset_name: gamercade_console-${{ matrix.release_suffix }}.exe
          asset_content_type: application/zip # required by GitHub API
